# ────────────────────────────────────────────────────────────────
# ─██████──██████─██████████████─██████─────────██████████████────
# ─██░░██──██░░██─██░░░░░░░░░░██─██░░██─────────██░░░░░░░░░░██────
# ─██░░██──██░░██─██░░██████░░██─██░░██─────────██░░██████░░██────
# ─██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────
# ─██░░██████░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────
# ─██░░░░░░░░░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────
# ─██░░██████░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────
# ─██░░██──██░░██─██░░██──██░░██─██░░██─────────██░░██──██░░██────
# ─██░░██──██░░██─██░░██████░░██─██░░██████████─██░░██████░░██────
# ─██░░██──██░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██────
# ─██████──██████─██████████████─██████████████─██████████████────
# ────────────────────────────────────────────────────────────────
# ────────────────────────────────────────────────────────────────────────────────
# ─██████████████───██████─────────██████████████─██████████████─██████──████████─
# ─██░░░░░░░░░░██───██░░██─────────██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░░░██─
# ─██░░██████░░██───██░░██─────────██░░██████░░██─██░░██████████─██░░██──██░░████─
# ─██░░██──██░░██───██░░██─────────██░░██──██░░██─██░░██─────────██░░██──██░░██───
# ─██░░██████░░████─██░░██─────────██░░██──██░░██─██░░██─────────██░░██████░░██───
# ─██░░░░░░░░░░░░██─██░░██─────────██░░██──██░░██─██░░██─────────██░░░░░░░░░░██───
# ─██░░████████░░██─██░░██─────────██░░██──██░░██─██░░██─────────██░░██████░░██───
# ─██░░██────██░░██─██░░██─────────██░░██──██░░██─██░░██─────────██░░██──██░░██───
# ─██░░████████░░██─██░░██████████─██░░██████░░██─██░░██████████─██░░██──██░░████─
# ─██░░░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░░░░░░░░░██─██░░██──██░░░░██─
# ─████████████████─██████████████─██████████████─██████████████─██████──████████─
# ────────────────────────────────────────────────────────────────────────────────

pluginPrefix: '&8&l<&bHoloBlock&8&l> &e'
locales: EN
worldguard-override: false
holo:
  default_offset: 1.8
  default_line:
  - '&7Right-Click On My Head To Edit Me'
  max_line: 100
  max_owned: 10
  max_member: 5
  max_text: 1000
  item:
    cost: 1000
    head: SecurityCamera
    displayname: '&7&k||&r &6&lHologram Head &7&k||'
    description:
    - '&7&m------------------------------'
    - ''
    - '&eThis Is Portable &6Hologram Head'
    - '&eInvented By &6&lEnrico &7Company'
    - '&ePlace It Anywhere You Want'
    - ''
    - '&7&m------------------------------'
LineItems:
- DIAMOND>2500
- IRON_INGOT>1500
- GOLD_INGOT>1500
- COAL>900
- REDSTONE>2000
- EMERALD>3000
- WOOL>500
- WOOL:2>500
- WOOL:3>500
- WOOL:4>500
- WOOL:5>500
- WOOL:6>500
- WOOL:7>500
- WOOL:8>500
- WOOL:9>500
- WOOL:10>500
- WOOL:11>500
- WOOL:12>500
- WOOL:13>500
- WOOL:14>500
- WOOL:15>500
- STAINED_GLASS>500
- STAINED_GLASS:1>500
- STAINED_GLASS:2>500
- STAINED_GLASS:3>500
- STAINED_GLASS:4>500
- STAINED_GLASS:5>500
- STAINED_GLASS:6>500
- STAINED_GLASS:7>500
- STAINED_GLASS:8>500
- STAINED_GLASS:9>500
- STAINED_GLASS:10>500
- STAINED_GLASS:11>500
- STAINED_GLASS:12>500
- STAINED_GLASS:13>500
- STAINED_GLASS:14>500
- STAINED_GLASS:15>500
- STAINED_GLASS_PANE>500
- STAINED_GLASS_PANE:1>500
- STAINED_GLASS_PANE:2>500
- STAINED_GLASS_PANE:3>500
- STAINED_GLASS_PANE:4>500
- STAINED_GLASS_PANE:5>500
- STAINED_GLASS_PANE:6>500
- STAINED_GLASS_PANE:7>500
- STAINED_GLASS_PANE:8>500
- STAINED_GLASS_PANE:9>500
- STAINED_GLASS_PANE:10>500
- STAINED_GLASS_PANE:11>500
- STAINED_GLASS_PANE:12>500
- STAINED_GLASS_PANE:13>500
- STAINED_GLASS_PANE:14>500
- STAINED_GLASS_PANE:15>500
CustomSkins:
  ARROW_LEFT:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_ArrowLeft
  ARROW_RIGHT:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_ArrowRight
  ARROW_UP:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_ArrowUP
  ARROW_DOWN:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_ArrowDown
  QUESTION:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_Question
  EXCLAMATION:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: name
    data: MHF_Exclamation
  MACHINE:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: encode
    data: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNmRkZDRhMTJkYTFjYzJjOWY5ZDZjZDQ5ZmM3NzhlM2ExMWYzNzU3ZGU2ZGQzMTJkNzBhMGQ0Nzg4NTE4OWMwIn19fQ==\
  BURGER:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: encode
    data: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMmVmNjMzNDNkMWZmMWVmY2FkNTQyYTE5MTAyMzdkNTMzYjVlMWQ1NDIxY2EyMzVlNWQxZWZjMDllNzA1NyJ9fX0=
  SMILE_PUMPKIN:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: encode
    data: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvMTJlYTk2ZjU0MGYxNzFkNmY2ODQ0NjY5YjE3NTNjZjQ4YThmNDE1ZThiYzM3YzhlZThiZjU2MWNhNmUzMWYyOCJ9fX0=
  BBQ:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: url
    data: http://textures.minecraft.net/texture/a86f19bf23d248e662c9c8b7fa15efb8a1f1d5bdacd3b8625a9b59e93ac8a
  KEYPAD:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    type: url
    data: http://textures.minecraft.net/texture/391b5e3a6db068a0331f31e87284e756e1f21a482d0731c2ef8ee6091f0433d
  MASTER_BALL:
    cost: 1000.0
    potions:
    - "INCREASE_DAMAGE:0"
    - "FAST_DIGGING:0"
    - "FIRE_RESISTANCE:0"
    - "SPEED:3"
    type: url
    data: http://textures.minecraft.net/texture/556d2a1cdda8778ffd833c7a5f539b87f99eb83a5d19599e5fa8e6c966c37c2
