name: HoloBlock
author: Onenrico
version: 2.0_Beta
description: Hologram Above Blocks !
main: me.onenrico.holoblock.main.Core
softdepend: [Vault, HolographicDisplays, Towny, Multiverse-Core]
commands:
  holoblock:
    description: The main command of holo block plugin
    aliases: hb