name: HoloBlock
author: Onenrico
version: 2.5.1
description: Hologram Above Blocks !
main: me.onenrico.holoblock.main.Core
softdepend: [Vault, HolographicDisplays, PlaceholderAPI, ProtocolLibs, HolographicExtension, Multiverse-Core, Towny, WorldGuard]
commands:
  holoblock:
    description: The main command of holo block plugin
    aliases: [hb, ob]